added eslint to precommit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,13 +1,53 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e # using the options command to abort script at first error
 echo
 echo "PRE-COMMIT"
 
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts\{0,1\}$")
+ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
+
+printf "\nValidating Javascript:\n"
+
+if [ "$STAGED_FILES" = "" ]; then
+  exit 0
+fi
+
+PASS=true
+
+# Check for eslint
+if [ ! -x "$ESLINT" ]; then
+  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
+  exit 1
+fi
+
+for FILE in $STAGED_FILES
+do
+  "$ESLINT" "$FILE"
+
+  if [[ "$?" == 0 ]]; then
+    printf "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    printf "\t\033[41mESLint Failed: $FILE\033[0m"
+    PASS=false
+  fi
+done
+
+printf "\nJavascript validation completed!\n"
+
+if ! $PASS; then
+  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
+else
+  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
+
+
+
 EMAIL=$(git config user.email)
 
 # make sure the user has registered a valid university email address
-if [[ $EMAIL != *"@coventry.ac.uk" ]]; then
+if [ $EMAIL != *"@coventry.ac.uk" ]; then
 	echo "  invalid config settings"
 	echo "  Your registered email is currently '$EMAIL'"
 	echo "  please run the following git commands:"
@@ -21,7 +61,7 @@ fi
 
 # see if the user is trying to merge a branch into master
 branch="$(git rev-parse --abbrev-ref HEAD)"
-if [[ $2 == 'merge' ]]; then
+if [ $2 == 'merge' ]; then
 	echo "merging branch"
 	if [[ "$branch" == "master" ]]; then
 		echo "  trying to merge into the 'master' branch"
@@ -49,28 +89,15 @@ fi
 # echo "parent branch is $PARENT")
 
 # see if the user is trying to commit to the master branch
-# echo "  you are trying to commit to the '$branch' branch"
-# if [ "$branch" = "master" ]; then
-#   echo "    you can't commit directly to the master branch"
-#   echo "    create a local feature branch first"
-#   echo
-#   exit 1
-# fi
+echo "  you are trying to commit to the '$branch' branch"
+if [ "$branch" = "master" ]; then
+  echo "    you can't commit directly to the master branch"
+  echo "    create a local feature branch first"
+  echo
+  exit 1
+  fi
 
-# check for valid branch name:
-
-# valid_branch_regex="^iss\d{3}\/[a-z\-]+$"
-
-# if [[ ! $local_branch =~ $valid_branch_regex ]]
-# then
-#     echo "invalid branch name"
-#     echo "  format is: 'iss000/issue-name'"
-#     echo "  replacing '000' with the issue number and 'issue-name' with the issue name"
-#     echo "  only lower-case letters and replace spaces in the issue name with dashes"
-#     echo "  rename your branch and try again"
-#     exit 1
-# fi
-
-./node_modules/.bin/eslint .
 
 echo "  commit successful..."
+
+exit $?
